name: Build and Push ComfyUI Docker Image

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab
  push:
    branches:
      - main # Triggers on pushes to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --- CRUCIAL: Clear Runner Space ---
      - name: Clear space to remove unused folders
        run: |
          echo "Starting cleanup..."
          # Remove large toolsets using sudo
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          echo "Cleanup complete."
          # Optional: Show free space after cleanup
          echo "Available disk space after cleanup:"
          df -h

      # --- Docker Setup ---
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx # Give the step an id to reference its outputs
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- Build and Push ---
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Use current directory as context
          file: ./Dockerfile # Path to your Dockerfile (capital D now)
          push: true # Actually push the image
          tags: robertvoy/comfyui-pod-wan:latest # Your image name and tag
          builder: ${{ steps.buildx.outputs.name }} # Use the buildx builder
          # Optional: Enable build caching using GitHub Actions Cache
          # cache-from: type=gha
          # cache-to: type=gha,mode=max